config/routes.rb
LemuredWebsite::Application.routes.draw do
  resources :users
  
  match '/signup', :to => 'users#new'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110430041448
#
# Table name: users
#
#  id         :integer         not null, primary key
#  loginname  :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'
class User < ActiveRecord::Base
	attr_accessor   :password
	attr_accessible :loginname, :email, :password, :password_confirmation
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	loginname_regex = /\A[\w\d]+\z/i
	password_regex = /\A(?=.*[\d])(?=.*[A-Z])([1-zA-Z0-1@*#$.]{6,20})\z/
	
	validates :loginname, :presence     => true,
					      :format       => { :with => loginname_regex },
						  :length       => { :maximum => 30},
						  :uniqueness   => { :case_sensitive => false }
	validates :email,     :presence     => true,
                          :format       => { :with => email_regex },
                          :uniqueness   => { :case_sensitive => false }
    validates :password,  :presence     => true,
                          :confirmation => true,
                          :length       => { :within => 6..20 },
                          :format       => { :with => password_regex }
                          
    before_save :encrypt_password
    
    def has_password?(submitted_password)
    	encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil  if user.nil?
		return user if user.has_password?(submitted_password)
	end
    
    private
    
      def encrypt_password 
    	self.salt = make_salt if new_record?
      	self.encrypted_password = encrypt(password)
  	  end
  	  
  	  def encrypt(string)
  	  	secure_hash("#{salt}--#{string}")
  	  end
  	  
  	  def make_salt
  	  	secure_hash("#{Time.now.utc}--#{password}")
  	  end
  	  
  	  def secure_hash(string)
  	  	Digest::SHA2.hexdigest(string)
  	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
    @title = "Home"
  end

  def contact
  	@title = "Contact"
  end
  
  def about
  	@title = "About"
  end
  
  def help
  	@title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  def show
  	@user = User.find(params[:id])
  	@title = @user.loginname
  end	
  def new
  	@title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.loginname,
												:class => 'gravatar',
												:gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<% logo = image_tag("LEMUREDWORD.PNG", :alt => "Lemured", :class => "round") %>
<%= link_to logo, root_path %>
<nav class="signin round">
  <ul>  	  		
    <li><%= link_to "Sign in", '#' %></li>
    <li class="or">or</li>
    <li><%= link_to "Sign up", signup_path %></li>
  </ul>
</nav>
<nav class="menu round">
  <ul class="menu round">
    <li><%= link_to "Home", root_path%></li>
    <li><%= link_to "Art Gallery", '#' %></li>
    <li><%= link_to "2D Gallery", '#' %></li>
    <li class="Search_bar"><%= link_to "Search", '#' %></li>
  </ul>	
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Lemured | <%= @title %></title>
	  <%= csrf_meta_tag %>
	  <%= render 'layouts/stylesheets' %>	  
	</head>
	<body>
	  <div class="container">
	  	<%= render 'layouts/header' %>
	    <section class="round">	
	      <%= yield %>
	    </section>
	    <%= render 'layouts/footer' %>
	    <%= debug(params) if Rails.env.development?%>
	  </div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
  <p>
	This is the about page for the 
	<a href="http://lemured.com/">Lemured</a> Website. 
  </p>

app/views/pages/contact.html.erb
<h1>Contact us</h1>
  <p>
	This is the contact page for the 
	<a href="http://lemured.com/">Lemured</a> Website. 
  </p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Thank you for hitting the <a href="/help">help page</a> we will be up soon.
</p>

app/views/pages/home.html.erb
<h1>Lemured</h1>
  <p>
    This is the homepage for the 
	<a href="http://lemured.com/">Lemured</a> Website. 
  </p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user, :default => 'identicon' %>
				<%= @user.loginname %>
			</h1>
		</td>
		<td class="company_links">
			<strong>Name</strong> <%= @user.loginname %><br />
			<strong>URL</strong>  <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>
<table class="profile_data" summary="Profile Data">
		<td class="posts round">
			<strong>Posts</strong>
		</td>
		<td class="right-sidebar round">
			<strong>Name</strong> <%= @user.loginname %><br />
			<strong>URL</strong>  <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>